version: '3.4'

services:

  fleaMarket_mongodb:
    image: mongo:latest
    container_name: FleaMarket_MongoDB
    ports:
      - 27317:27017
    environment:
      - TZ=Asia/Shanghai
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=Password123
    volumes:
      - .\MongoDB\data:/data/db